import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { motion } from 'framer-motion'
import { Box } from "@mui/system";
import { Container, List, ListItem, ListItemText } from "@mui/material";

export default function Index() {
  return (
    <div className={styles.container}>
      <Head>
        <title>POKEEEMI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous"></link>
      </Head>

      <main className={styles.main}>
        <motion.div initial="hidden" animate="visible" variants={{
          hidden: {
            scale: .8,
            opacity: 0
          },
          visible: {
            scale: 1,
            opacity: 1, 
            transition: {
              delay: .4
            }
          }
        }}>
          <h1 className={styles.title}>
            Bienvenue sur POKE-EEMI
          </h1>
        </motion.div>

        <Container>
          <Box sx={{
            border: "1px solid",
            borderRadius: '15px!important',
            bgcolor: '#1776D2',
            color: 'white',
            mt: '70px',
            mb: '50px',
          }}
          >
            <List>
              <ListItem sx={{
                mt: '20px',
              }}>
                <ListItemText
                  primary="Ce projet a été réalisé par LUCHMUN Dylan validant son mastère CTO Tech Lead à l'EEMI."
                />
              </ListItem>
              <ListItem>
                <ListItemText
                  primary="Ce projet est un Pokedex listant tous les Pokemon grâce à l'API PokeApi répondant aux attentes du cours développement frontend."
                />
              </ListItem>
              <ListItem>
                <ListItemText
                  primary="Ici, vous êtes sur la page d'accueil du site. Pour vous rendre sur le Pokedex, merci de cliquez sur le bouton ci-dessous."
                />
              </ListItem>
              <ListItem>
                <ListItemText
                  primary="Sur ce projet, une page sera consacré à la liste des Pokémon auquel nous pourrons obtenir de multiples informations en cliquant dessus (description)."
                />
              </ListItem>
              <ListItem>
                <ListItemText
                  primary="De même, nous pouvons filtrer les Pokémon en fonction de la génération."
                />
              </ListItem>
              <ListItem>
                <ListItemText
                  primary="Vous pourrez retrouver un footer avec différents liens notamment une page de formulaire et des mentions légales, mais aussi une animation en ayant utilisé framer-motion."
                />
              </ListItem>
              <ListItem>
                <ListItemText
                  primary="En vous souhaitant une bonne navigation."
                />
              </ListItem>
            </List>
            <div className={styles.cardhome}>
              <div className="card">
                <div className={styles.cardcustom}>
                  <div className="card-body card-poke d-flex justify-content-center">
                    <a href="home" className={styles.titlepoke}>Accéder au Pokédex</a>
                  </div>
                </div>
              </div>
            </div>
          </Box>
        </Container>
      </main>

      <footer className={styles.footer}>
        <a
          href="contact"
          target="_blank"
          rel="noopener noreferrer"
          className={styles.ahref}
        >
          Nous contacter
        </a>
        <a
          href="legal"
          target="_blank"
          rel="noopener noreferrer"
          className={styles.ahref}
        >
          Mentions légales
        </a>
        <a
          href="https://eemi.com"
          target="_blank"
          rel="noopener noreferrer"
          className={styles.ahref}
        >
          EEMI
        </a>
      </footer>
    </div>
  )
}